[package]
name = "watermark_pro"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.29.1"
image = { version = "0.25.5", features = ["jpeg", "png", "webp"] }
rfd = "0.15.2"
walkdir = "2.5.0"
fast_image_resize = "5.0"
rawloader = "0.37" # <--- Back to the modern version